// Copyright © 2024 Luther Systems, Ltd. All rights reserved.
// API Models and Documentation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pb/v1/oracle.proto

package v1

import (
	v1 "buf.build/gen/go/luthersystems/protos/protocolbuffers/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadClaimWF1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   string                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	PolicyId      string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF1Request) Reset() {
	*x = UploadClaimWF1Request{}
	mi := &file_pb_v1_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF1Request) ProtoMessage() {}

func (x *UploadClaimWF1Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF1Request.ProtoReflect.Descriptor instead.
func (*UploadClaimWF1Request) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *UploadClaimWF1Request) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

func (x *UploadClaimWF1Request) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type UploadClaimWF1Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UploadClaimWF1Response_Exception
	Result        isUploadClaimWF1Response_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF1Response) Reset() {
	*x = UploadClaimWF1Response{}
	mi := &file_pb_v1_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF1Response) ProtoMessage() {}

func (x *UploadClaimWF1Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF1Response.ProtoReflect.Descriptor instead.
func (*UploadClaimWF1Response) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *UploadClaimWF1Response) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF1Response) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UploadClaimWF1Response) GetResult() isUploadClaimWF1Response_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UploadClaimWF1Response) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*UploadClaimWF1Response_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isUploadClaimWF1Response_Result interface {
	isUploadClaimWF1Response_Result()
}

type UploadClaimWF1Response_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*UploadClaimWF1Response_Exception) isUploadClaimWF1Response_Result() {}

type UploadClaimWF2Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   string                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	PolicyId      string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF2Request) Reset() {
	*x = UploadClaimWF2Request{}
	mi := &file_pb_v1_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF2Request) ProtoMessage() {}

func (x *UploadClaimWF2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF2Request.ProtoReflect.Descriptor instead.
func (*UploadClaimWF2Request) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *UploadClaimWF2Request) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

func (x *UploadClaimWF2Request) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type UploadClaimWF2Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UploadClaimWF2Response_Exception
	Result        isUploadClaimWF2Response_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF2Response) Reset() {
	*x = UploadClaimWF2Response{}
	mi := &file_pb_v1_oracle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF2Response) ProtoMessage() {}

func (x *UploadClaimWF2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF2Response.ProtoReflect.Descriptor instead.
func (*UploadClaimWF2Response) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *UploadClaimWF2Response) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF2Response) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UploadClaimWF2Response) GetResult() isUploadClaimWF2Response_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UploadClaimWF2Response) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*UploadClaimWF2Response_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isUploadClaimWF2Response_Result interface {
	isUploadClaimWF2Response_Result()
}

type UploadClaimWF2Response_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*UploadClaimWF2Response_Exception) isUploadClaimWF2Response_Result() {}

type UploadClaimWF3Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   string                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	PolicyId      string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF3Request) Reset() {
	*x = UploadClaimWF3Request{}
	mi := &file_pb_v1_oracle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF3Request) ProtoMessage() {}

func (x *UploadClaimWF3Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF3Request.ProtoReflect.Descriptor instead.
func (*UploadClaimWF3Request) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{4}
}

func (x *UploadClaimWF3Request) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

func (x *UploadClaimWF3Request) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type UploadClaimWF3Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UploadClaimWF3Response_Exception
	Result        isUploadClaimWF3Response_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF3Response) Reset() {
	*x = UploadClaimWF3Response{}
	mi := &file_pb_v1_oracle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF3Response) ProtoMessage() {}

func (x *UploadClaimWF3Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF3Response.ProtoReflect.Descriptor instead.
func (*UploadClaimWF3Response) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{5}
}

func (x *UploadClaimWF3Response) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF3Response) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UploadClaimWF3Response) GetResult() isUploadClaimWF3Response_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UploadClaimWF3Response) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*UploadClaimWF3Response_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isUploadClaimWF3Response_Result interface {
	isUploadClaimWF3Response_Result()
}

type UploadClaimWF3Response_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*UploadClaimWF3Response_Exception) isUploadClaimWF3Response_Result() {}

type UploadClaimWF4Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   string                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	PolicyId      string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF4Request) Reset() {
	*x = UploadClaimWF4Request{}
	mi := &file_pb_v1_oracle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF4Request) ProtoMessage() {}

func (x *UploadClaimWF4Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF4Request.ProtoReflect.Descriptor instead.
func (*UploadClaimWF4Request) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{6}
}

func (x *UploadClaimWF4Request) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

func (x *UploadClaimWF4Request) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type UploadClaimWF4Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UploadClaimWF4Response_Exception
	Result        isUploadClaimWF4Response_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF4Response) Reset() {
	*x = UploadClaimWF4Response{}
	mi := &file_pb_v1_oracle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF4Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF4Response) ProtoMessage() {}

func (x *UploadClaimWF4Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF4Response.ProtoReflect.Descriptor instead.
func (*UploadClaimWF4Response) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{7}
}

func (x *UploadClaimWF4Response) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF4Response) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UploadClaimWF4Response) GetResult() isUploadClaimWF4Response_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UploadClaimWF4Response) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*UploadClaimWF4Response_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isUploadClaimWF4Response_Result interface {
	isUploadClaimWF4Response_Result()
}

type UploadClaimWF4Response_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*UploadClaimWF4Response_Exception) isUploadClaimWF4Response_Result() {}

type UploadClaimWF5Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   string                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	PolicyId      string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF5Request) Reset() {
	*x = UploadClaimWF5Request{}
	mi := &file_pb_v1_oracle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF5Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF5Request) ProtoMessage() {}

func (x *UploadClaimWF5Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF5Request.ProtoReflect.Descriptor instead.
func (*UploadClaimWF5Request) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{8}
}

func (x *UploadClaimWF5Request) GetFileContent() string {
	if x != nil {
		return x.FileContent
	}
	return ""
}

func (x *UploadClaimWF5Request) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type UploadClaimWF5Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UploadClaimWF5Response_Exception
	Result        isUploadClaimWF5Response_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF5Response) Reset() {
	*x = UploadClaimWF5Response{}
	mi := &file_pb_v1_oracle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF5Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF5Response) ProtoMessage() {}

func (x *UploadClaimWF5Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF5Response.ProtoReflect.Descriptor instead.
func (*UploadClaimWF5Response) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{9}
}

func (x *UploadClaimWF5Response) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF5Response) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UploadClaimWF5Response) GetResult() isUploadClaimWF5Response_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UploadClaimWF5Response) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*UploadClaimWF5Response_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isUploadClaimWF5Response_Result interface {
	isUploadClaimWF5Response_Result()
}

type UploadClaimWF5Response_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*UploadClaimWF5Response_Exception) isUploadClaimWF5Response_Result() {}

var File_pb_v1_oracle_proto protoreflect.FileDescriptor

const file_pb_v1_oracle_proto_rawDesc = "" +
	"\n" +
	"\x12pb/v1/oracle.proto\x12\x05pb.v1\x1a\x19common/v1/exception.proto\"W\n" +
	"\x15UploadClaimWF1Request\x12!\n" +
	"\ffile_content\x18\x01 \x01(\tR\vfileContent\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\"\x89\x01\n" +
	"\x16UploadClaimWF1Response\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06result\"W\n" +
	"\x15UploadClaimWF2Request\x12!\n" +
	"\ffile_content\x18\x01 \x01(\tR\vfileContent\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\"\x89\x01\n" +
	"\x16UploadClaimWF2Response\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06result\"W\n" +
	"\x15UploadClaimWF3Request\x12!\n" +
	"\ffile_content\x18\x01 \x01(\tR\vfileContent\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\"\x89\x01\n" +
	"\x16UploadClaimWF3Response\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06result\"W\n" +
	"\x15UploadClaimWF4Request\x12!\n" +
	"\ffile_content\x18\x01 \x01(\tR\vfileContent\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\"\x89\x01\n" +
	"\x16UploadClaimWF4Response\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06result\"W\n" +
	"\x15UploadClaimWF5Request\x12!\n" +
	"\ffile_content\x18\x01 \x01(\tR\vfileContent\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\"\x89\x01\n" +
	"\x16UploadClaimWF5Response\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06resultBy\n" +
	"\tcom.pb.v1B\vOracleProtoP\x01Z*github.com/luthersystems/sandbox/api/pb/v1\xa2\x02\x03PXX\xaa\x02\x05Pb.V1\xca\x02\x05Pb\\V1\xe2\x02\x11Pb\\V1\\GPBMetadata\xea\x02\x06Pb::V1b\x06proto3"

var (
	file_pb_v1_oracle_proto_rawDescOnce sync.Once
	file_pb_v1_oracle_proto_rawDescData []byte
)

func file_pb_v1_oracle_proto_rawDescGZIP() []byte {
	file_pb_v1_oracle_proto_rawDescOnce.Do(func() {
		file_pb_v1_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_v1_oracle_proto_rawDesc), len(file_pb_v1_oracle_proto_rawDesc)))
	})
	return file_pb_v1_oracle_proto_rawDescData
}

var file_pb_v1_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_v1_oracle_proto_goTypes = []any{
	(*UploadClaimWF1Request)(nil),  // 0: pb.v1.UploadClaimWF1Request
	(*UploadClaimWF1Response)(nil), // 1: pb.v1.UploadClaimWF1Response
	(*UploadClaimWF2Request)(nil),  // 2: pb.v1.UploadClaimWF2Request
	(*UploadClaimWF2Response)(nil), // 3: pb.v1.UploadClaimWF2Response
	(*UploadClaimWF3Request)(nil),  // 4: pb.v1.UploadClaimWF3Request
	(*UploadClaimWF3Response)(nil), // 5: pb.v1.UploadClaimWF3Response
	(*UploadClaimWF4Request)(nil),  // 6: pb.v1.UploadClaimWF4Request
	(*UploadClaimWF4Response)(nil), // 7: pb.v1.UploadClaimWF4Response
	(*UploadClaimWF5Request)(nil),  // 8: pb.v1.UploadClaimWF5Request
	(*UploadClaimWF5Response)(nil), // 9: pb.v1.UploadClaimWF5Response
	(*v1.Exception)(nil),           // 10: common.v1.Exception
}
var file_pb_v1_oracle_proto_depIdxs = []int32{
	10, // 0: pb.v1.UploadClaimWF1Response.exception:type_name -> common.v1.Exception
	10, // 1: pb.v1.UploadClaimWF2Response.exception:type_name -> common.v1.Exception
	10, // 2: pb.v1.UploadClaimWF3Response.exception:type_name -> common.v1.Exception
	10, // 3: pb.v1.UploadClaimWF4Response.exception:type_name -> common.v1.Exception
	10, // 4: pb.v1.UploadClaimWF5Response.exception:type_name -> common.v1.Exception
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pb_v1_oracle_proto_init() }
func file_pb_v1_oracle_proto_init() {
	if File_pb_v1_oracle_proto != nil {
		return
	}
	file_pb_v1_oracle_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadClaimWF1Response_Exception)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[3].OneofWrappers = []any{
		(*UploadClaimWF2Response_Exception)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[5].OneofWrappers = []any{
		(*UploadClaimWF3Response_Exception)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[7].OneofWrappers = []any{
		(*UploadClaimWF4Response_Exception)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[9].OneofWrappers = []any{
		(*UploadClaimWF5Response_Exception)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_oracle_proto_rawDesc), len(file_pb_v1_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_v1_oracle_proto_goTypes,
		DependencyIndexes: file_pb_v1_oracle_proto_depIdxs,
		MessageInfos:      file_pb_v1_oracle_proto_msgTypes,
	}.Build()
	File_pb_v1_oracle_proto = out.File
	file_pb_v1_oracle_proto_goTypes = nil
	file_pb_v1_oracle_proto_depIdxs = nil
}
