// Copyright © 2024 Luther Systems, Ltd. All rights reserved.
// API Models and Documentation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pb/v1/oracle.proto

package v1

import (
	v1 "buf.build/gen/go/luthersystems/protos/protocolbuffers/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadClaimWF1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF1Request) Reset() {
	*x = UploadClaimWF1Request{}
	mi := &file_pb_v1_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF1Request) ProtoMessage() {}

func (x *UploadClaimWF1Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF1Request.ProtoReflect.Descriptor instead.
func (*UploadClaimWF1Request) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *UploadClaimWF1Request) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type UploadClaimWF1Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UploadClaimWF1Response_Exception
	Result        isUploadClaimWF1Response_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF1Response) Reset() {
	*x = UploadClaimWF1Response{}
	mi := &file_pb_v1_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF1Response) ProtoMessage() {}

func (x *UploadClaimWF1Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF1Response.ProtoReflect.Descriptor instead.
func (*UploadClaimWF1Response) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *UploadClaimWF1Response) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF1Response) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UploadClaimWF1Response) GetResult() isUploadClaimWF1Response_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UploadClaimWF1Response) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*UploadClaimWF1Response_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isUploadClaimWF1Response_Result interface {
	isUploadClaimWF1Response_Result()
}

type UploadClaimWF1Response_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*UploadClaimWF1Response_Exception) isUploadClaimWF1Response_Result() {}

type UploadClaimWF2Request struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PolicyId         string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	GuidewireClaimId string                 `protobuf:"bytes,2,opt,name=guidewire_claim_id,json=guidewireClaimId,proto3" json:"guidewire_claim_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UploadClaimWF2Request) Reset() {
	*x = UploadClaimWF2Request{}
	mi := &file_pb_v1_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF2Request) ProtoMessage() {}

func (x *UploadClaimWF2Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF2Request.ProtoReflect.Descriptor instead.
func (*UploadClaimWF2Request) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *UploadClaimWF2Request) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *UploadClaimWF2Request) GetGuidewireClaimId() string {
	if x != nil {
		return x.GuidewireClaimId
	}
	return ""
}

type UploadClaimWF2Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UploadClaimWF2Response_Exception
	Result        isUploadClaimWF2Response_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF2Response) Reset() {
	*x = UploadClaimWF2Response{}
	mi := &file_pb_v1_oracle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF2Response) ProtoMessage() {}

func (x *UploadClaimWF2Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF2Response.ProtoReflect.Descriptor instead.
func (*UploadClaimWF2Response) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *UploadClaimWF2Response) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF2Response) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UploadClaimWF2Response) GetResult() isUploadClaimWF2Response_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UploadClaimWF2Response) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*UploadClaimWF2Response_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isUploadClaimWF2Response_Result interface {
	isUploadClaimWF2Response_Result()
}

type UploadClaimWF2Response_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*UploadClaimWF2Response_Exception) isUploadClaimWF2Response_Result() {}

type UploadClaimWF3Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClaimId        string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	InvoiceAmount  string                 `protobuf:"bytes,2,opt,name=invoice_amount,json=invoiceAmount,proto3" json:"invoice_amount,omitempty"` // or double
	SignerName     string                 `protobuf:"bytes,3,opt,name=signer_name,json=signerName,proto3" json:"signer_name,omitempty"`
	SignerEmail    string                 `protobuf:"bytes,4,opt,name=signer_email,json=signerEmail,proto3" json:"signer_email,omitempty"`
	OriginatorName string                 `protobuf:"bytes,5,opt,name=originator_name,json=originatorName,proto3" json:"originator_name,omitempty"` // optional
	RecipientName  string                 `protobuf:"bytes,6,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`    // optional
	IssueDate      string                 `protobuf:"bytes,7,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`                // YYYY-MM-DD
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadClaimWF3Request) Reset() {
	*x = UploadClaimWF3Request{}
	mi := &file_pb_v1_oracle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF3Request) ProtoMessage() {}

func (x *UploadClaimWF3Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF3Request.ProtoReflect.Descriptor instead.
func (*UploadClaimWF3Request) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{4}
}

func (x *UploadClaimWF3Request) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF3Request) GetInvoiceAmount() string {
	if x != nil {
		return x.InvoiceAmount
	}
	return ""
}

func (x *UploadClaimWF3Request) GetSignerName() string {
	if x != nil {
		return x.SignerName
	}
	return ""
}

func (x *UploadClaimWF3Request) GetSignerEmail() string {
	if x != nil {
		return x.SignerEmail
	}
	return ""
}

func (x *UploadClaimWF3Request) GetOriginatorName() string {
	if x != nil {
		return x.OriginatorName
	}
	return ""
}

func (x *UploadClaimWF3Request) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *UploadClaimWF3Request) GetIssueDate() string {
	if x != nil {
		return x.IssueDate
	}
	return ""
}

type UploadClaimWF3Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UploadClaimWF3Response_Exception
	Result        isUploadClaimWF3Response_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF3Response) Reset() {
	*x = UploadClaimWF3Response{}
	mi := &file_pb_v1_oracle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF3Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF3Response) ProtoMessage() {}

func (x *UploadClaimWF3Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF3Response.ProtoReflect.Descriptor instead.
func (*UploadClaimWF3Response) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{5}
}

func (x *UploadClaimWF3Response) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF3Response) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UploadClaimWF3Response) GetResult() isUploadClaimWF3Response_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UploadClaimWF3Response) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*UploadClaimWF3Response_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isUploadClaimWF3Response_Result interface {
	isUploadClaimWF3Response_Result()
}

type UploadClaimWF3Response_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*UploadClaimWF3Response_Exception) isUploadClaimWF3Response_Result() {}

// Line item for Zoho invoice
type LineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineItem) Reset() {
	*x = LineItem{}
	mi := &file_pb_v1_oracle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineItem) ProtoMessage() {}

func (x *LineItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineItem.ProtoReflect.Descriptor instead.
func (*LineItem) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{6}
}

func (x *LineItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LineItem) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *LineItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UploadClaimWF4Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: defaults to "POL-8872" if not provided
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Zoho invoice fields
	CustomerId      string      `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`                // Required: Zoho customer ID
	ReferenceNumber string      `protobuf:"bytes,3,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"` // Required: Claim reference number (used as claim_id if claim_id not provided)
	DueDate         string      `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`                         // Required: Invoice due date (YYYY-MM-DD)
	IsInclusiveTax  bool        `protobuf:"varint,5,opt,name=is_inclusive_tax,json=isInclusiveTax,proto3" json:"is_inclusive_tax,omitempty"` // Required: Whether tax is inclusive
	LineItems       []*LineItem `protobuf:"bytes,6,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`                   // Required: Invoice line items
	// Optional overrides
	ClaimId       string `protobuf:"bytes,7,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`                // Optional: Override claim_id (defaults to reference_number)
	CurrencyCode  string `protobuf:"bytes,8,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"` // Optional: Currency code (defaults to "GBP")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF4Request) Reset() {
	*x = UploadClaimWF4Request{}
	mi := &file_pb_v1_oracle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF4Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF4Request) ProtoMessage() {}

func (x *UploadClaimWF4Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF4Request.ProtoReflect.Descriptor instead.
func (*UploadClaimWF4Request) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{7}
}

func (x *UploadClaimWF4Request) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *UploadClaimWF4Request) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UploadClaimWF4Request) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *UploadClaimWF4Request) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *UploadClaimWF4Request) GetIsInclusiveTax() bool {
	if x != nil {
		return x.IsInclusiveTax
	}
	return false
}

func (x *UploadClaimWF4Request) GetLineItems() []*LineItem {
	if x != nil {
		return x.LineItems
	}
	return nil
}

func (x *UploadClaimWF4Request) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF4Request) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

type UploadClaimWF4Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UploadClaimWF4Response_Exception
	Result        isUploadClaimWF4Response_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF4Response) Reset() {
	*x = UploadClaimWF4Response{}
	mi := &file_pb_v1_oracle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF4Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF4Response) ProtoMessage() {}

func (x *UploadClaimWF4Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF4Response.ProtoReflect.Descriptor instead.
func (*UploadClaimWF4Response) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{8}
}

func (x *UploadClaimWF4Response) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF4Response) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UploadClaimWF4Response) GetResult() isUploadClaimWF4Response_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UploadClaimWF4Response) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*UploadClaimWF4Response_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isUploadClaimWF4Response_Result interface {
	isUploadClaimWF4Response_Result()
}

type UploadClaimWF4Response_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*UploadClaimWF4Response_Exception) isUploadClaimWF4Response_Result() {}

type UploadClaimWF5Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF5Request) Reset() {
	*x = UploadClaimWF5Request{}
	mi := &file_pb_v1_oracle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF5Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF5Request) ProtoMessage() {}

func (x *UploadClaimWF5Request) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF5Request.ProtoReflect.Descriptor instead.
func (*UploadClaimWF5Request) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{9}
}

func (x *UploadClaimWF5Request) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type UploadClaimWF5Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*UploadClaimWF5Response_Exception
	Result        isUploadClaimWF5Response_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClaimWF5Response) Reset() {
	*x = UploadClaimWF5Response{}
	mi := &file_pb_v1_oracle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClaimWF5Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClaimWF5Response) ProtoMessage() {}

func (x *UploadClaimWF5Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClaimWF5Response.ProtoReflect.Descriptor instead.
func (*UploadClaimWF5Response) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{10}
}

func (x *UploadClaimWF5Response) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *UploadClaimWF5Response) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UploadClaimWF5Response) GetResult() isUploadClaimWF5Response_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UploadClaimWF5Response) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*UploadClaimWF5Response_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isUploadClaimWF5Response_Result interface {
	isUploadClaimWF5Response_Result()
}

type UploadClaimWF5Response_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*UploadClaimWF5Response_Exception) isUploadClaimWF5Response_Result() {}

type InvokeProcessRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PolicyId         string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`                           // Required
	GuidewireClaimId string                 `protobuf:"bytes,2,opt,name=guidewire_claim_id,json=guidewireClaimId,proto3" json:"guidewire_claim_id,omitempty"` // Optional
	GwClaimId        string                 `protobuf:"bytes,3,opt,name=gw_claim_id,json=gwClaimId,proto3" json:"gw_claim_id,omitempty"`                      // Optional
	SignerEmail      string                 `protobuf:"bytes,4,opt,name=signer_email,json=signerEmail,proto3" json:"signer_email,omitempty"`                  // Optional
	SignerName       string                 `protobuf:"bytes,5,opt,name=signer_name,json=signerName,proto3" json:"signer_name,omitempty"`                     // Optional
	InvoiceAmount    string                 `protobuf:"bytes,6,opt,name=invoice_amount,json=invoiceAmount,proto3" json:"invoice_amount,omitempty"`            // Optional
	OriginatorName   string                 `protobuf:"bytes,7,opt,name=originator_name,json=originatorName,proto3" json:"originator_name,omitempty"`         // Optional
	RecipientName    string                 `protobuf:"bytes,8,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`            // Optional
	IssueDate        string                 `protobuf:"bytes,9,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`                        // Optional (YYYY-MM-DD)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvokeProcessRequest) Reset() {
	*x = InvokeProcessRequest{}
	mi := &file_pb_v1_oracle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeProcessRequest) ProtoMessage() {}

func (x *InvokeProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeProcessRequest.ProtoReflect.Descriptor instead.
func (*InvokeProcessRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{11}
}

func (x *InvokeProcessRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *InvokeProcessRequest) GetGuidewireClaimId() string {
	if x != nil {
		return x.GuidewireClaimId
	}
	return ""
}

func (x *InvokeProcessRequest) GetGwClaimId() string {
	if x != nil {
		return x.GwClaimId
	}
	return ""
}

func (x *InvokeProcessRequest) GetSignerEmail() string {
	if x != nil {
		return x.SignerEmail
	}
	return ""
}

func (x *InvokeProcessRequest) GetSignerName() string {
	if x != nil {
		return x.SignerName
	}
	return ""
}

func (x *InvokeProcessRequest) GetInvoiceAmount() string {
	if x != nil {
		return x.InvoiceAmount
	}
	return ""
}

func (x *InvokeProcessRequest) GetOriginatorName() string {
	if x != nil {
		return x.OriginatorName
	}
	return ""
}

func (x *InvokeProcessRequest) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *InvokeProcessRequest) GetIssueDate() string {
	if x != nil {
		return x.IssueDate
	}
	return ""
}

type InvokeProcessResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*InvokeProcessResponse_Exception
	Result        isInvokeProcessResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeProcessResponse) Reset() {
	*x = InvokeProcessResponse{}
	mi := &file_pb_v1_oracle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeProcessResponse) ProtoMessage() {}

func (x *InvokeProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeProcessResponse.ProtoReflect.Descriptor instead.
func (*InvokeProcessResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{12}
}

func (x *InvokeProcessResponse) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *InvokeProcessResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InvokeProcessResponse) GetResult() isInvokeProcessResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *InvokeProcessResponse) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*InvokeProcessResponse_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isInvokeProcessResponse_Result interface {
	isInvokeProcessResponse_Result()
}

type InvokeProcessResponse_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*InvokeProcessResponse_Exception) isInvokeProcessResponse_Result() {}

type GetClaimStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClaimId       string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"` // Required: Unique identifier of the claim
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClaimStateRequest) Reset() {
	*x = GetClaimStateRequest{}
	mi := &file_pb_v1_oracle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaimStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaimStateRequest) ProtoMessage() {}

func (x *GetClaimStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaimStateRequest.ProtoReflect.Descriptor instead.
func (*GetClaimStateRequest) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{13}
}

func (x *GetClaimStateRequest) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

type GetClaimStateResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ClaimId string                 `protobuf:"bytes,1,opt,name=claim_id,json=claimId,proto3" json:"claim_id,omitempty"`
	State   string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetClaimStateResponse_Exception
	Result        isGetClaimStateResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClaimStateResponse) Reset() {
	*x = GetClaimStateResponse{}
	mi := &file_pb_v1_oracle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaimStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaimStateResponse) ProtoMessage() {}

func (x *GetClaimStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_v1_oracle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaimStateResponse.ProtoReflect.Descriptor instead.
func (*GetClaimStateResponse) Descriptor() ([]byte, []int) {
	return file_pb_v1_oracle_proto_rawDescGZIP(), []int{14}
}

func (x *GetClaimStateResponse) GetClaimId() string {
	if x != nil {
		return x.ClaimId
	}
	return ""
}

func (x *GetClaimStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetClaimStateResponse) GetResult() isGetClaimStateResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetClaimStateResponse) GetException() *v1.Exception {
	if x != nil {
		if x, ok := x.Result.(*GetClaimStateResponse_Exception); ok {
			return x.Exception
		}
	}
	return nil
}

type isGetClaimStateResponse_Result interface {
	isGetClaimStateResponse_Result()
}

type GetClaimStateResponse_Exception struct {
	Exception *v1.Exception `protobuf:"bytes,3,opt,name=exception,proto3,oneof"`
}

func (*GetClaimStateResponse_Exception) isGetClaimStateResponse_Result() {}

var File_pb_v1_oracle_proto protoreflect.FileDescriptor

const file_pb_v1_oracle_proto_rawDesc = "" +
	"\n" +
	"\x12pb/v1/oracle.proto\x12\x05pb.v1\x1a\x19common/v1/exception.proto\"4\n" +
	"\x15UploadClaimWF1Request\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\"\x89\x01\n" +
	"\x16UploadClaimWF1Response\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06result\"b\n" +
	"\x15UploadClaimWF2Request\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12,\n" +
	"\x12guidewire_claim_id\x18\x02 \x01(\tR\x10guidewireClaimId\"\x89\x01\n" +
	"\x16UploadClaimWF2Response\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06result\"\x8c\x02\n" +
	"\x15UploadClaimWF3Request\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12%\n" +
	"\x0einvoice_amount\x18\x02 \x01(\tR\rinvoiceAmount\x12\x1f\n" +
	"\vsigner_name\x18\x03 \x01(\tR\n" +
	"signerName\x12!\n" +
	"\fsigner_email\x18\x04 \x01(\tR\vsignerEmail\x12'\n" +
	"\x0foriginator_name\x18\x05 \x01(\tR\x0eoriginatorName\x12%\n" +
	"\x0erecipient_name\x18\x06 \x01(\tR\rrecipientName\x12\x1d\n" +
	"\n" +
	"issue_date\x18\a \x01(\tR\tissueDate\"\x89\x01\n" +
	"\x16UploadClaimWF3Response\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06result\"N\n" +
	"\bLineItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\xb5\x02\n" +
	"\x15UploadClaimWF4Request\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12)\n" +
	"\x10reference_number\x18\x03 \x01(\tR\x0freferenceNumber\x12\x19\n" +
	"\bdue_date\x18\x04 \x01(\tR\adueDate\x12(\n" +
	"\x10is_inclusive_tax\x18\x05 \x01(\bR\x0eisInclusiveTax\x12.\n" +
	"\n" +
	"line_items\x18\x06 \x03(\v2\x0f.pb.v1.LineItemR\tlineItems\x12\x19\n" +
	"\bclaim_id\x18\a \x01(\tR\aclaimId\x12#\n" +
	"\rcurrency_code\x18\b \x01(\tR\fcurrencyCode\"\x89\x01\n" +
	"\x16UploadClaimWF4Response\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06result\"4\n" +
	"\x15UploadClaimWF5Request\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\"\x89\x01\n" +
	"\x16UploadClaimWF5Response\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06result\"\xdb\x02\n" +
	"\x14InvokeProcessRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12,\n" +
	"\x12guidewire_claim_id\x18\x02 \x01(\tR\x10guidewireClaimId\x12\x1e\n" +
	"\vgw_claim_id\x18\x03 \x01(\tR\tgwClaimId\x12!\n" +
	"\fsigner_email\x18\x04 \x01(\tR\vsignerEmail\x12\x1f\n" +
	"\vsigner_name\x18\x05 \x01(\tR\n" +
	"signerName\x12%\n" +
	"\x0einvoice_amount\x18\x06 \x01(\tR\rinvoiceAmount\x12'\n" +
	"\x0foriginator_name\x18\a \x01(\tR\x0eoriginatorName\x12%\n" +
	"\x0erecipient_name\x18\b \x01(\tR\rrecipientName\x12\x1d\n" +
	"\n" +
	"issue_date\x18\t \x01(\tR\tissueDate\"\x88\x01\n" +
	"\x15InvokeProcessResponse\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06result\"1\n" +
	"\x14GetClaimStateRequest\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\"\x88\x01\n" +
	"\x15GetClaimStateResponse\x12\x19\n" +
	"\bclaim_id\x18\x01 \x01(\tR\aclaimId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x124\n" +
	"\texception\x18\x03 \x01(\v2\x14.common.v1.ExceptionH\x00R\texceptionB\b\n" +
	"\x06resultBv\n" +
	"\tcom.pb.v1B\vOracleProtoP\x01Z'github.com/luthersystems/cdcs/api/pb/v1\xa2\x02\x03PXX\xaa\x02\x05Pb.V1\xca\x02\x05Pb\\V1\xe2\x02\x11Pb\\V1\\GPBMetadata\xea\x02\x06Pb::V1b\x06proto3"

var (
	file_pb_v1_oracle_proto_rawDescOnce sync.Once
	file_pb_v1_oracle_proto_rawDescData []byte
)

func file_pb_v1_oracle_proto_rawDescGZIP() []byte {
	file_pb_v1_oracle_proto_rawDescOnce.Do(func() {
		file_pb_v1_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_v1_oracle_proto_rawDesc), len(file_pb_v1_oracle_proto_rawDesc)))
	})
	return file_pb_v1_oracle_proto_rawDescData
}

var file_pb_v1_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pb_v1_oracle_proto_goTypes = []any{
	(*UploadClaimWF1Request)(nil),  // 0: pb.v1.UploadClaimWF1Request
	(*UploadClaimWF1Response)(nil), // 1: pb.v1.UploadClaimWF1Response
	(*UploadClaimWF2Request)(nil),  // 2: pb.v1.UploadClaimWF2Request
	(*UploadClaimWF2Response)(nil), // 3: pb.v1.UploadClaimWF2Response
	(*UploadClaimWF3Request)(nil),  // 4: pb.v1.UploadClaimWF3Request
	(*UploadClaimWF3Response)(nil), // 5: pb.v1.UploadClaimWF3Response
	(*LineItem)(nil),               // 6: pb.v1.LineItem
	(*UploadClaimWF4Request)(nil),  // 7: pb.v1.UploadClaimWF4Request
	(*UploadClaimWF4Response)(nil), // 8: pb.v1.UploadClaimWF4Response
	(*UploadClaimWF5Request)(nil),  // 9: pb.v1.UploadClaimWF5Request
	(*UploadClaimWF5Response)(nil), // 10: pb.v1.UploadClaimWF5Response
	(*InvokeProcessRequest)(nil),   // 11: pb.v1.InvokeProcessRequest
	(*InvokeProcessResponse)(nil),  // 12: pb.v1.InvokeProcessResponse
	(*GetClaimStateRequest)(nil),   // 13: pb.v1.GetClaimStateRequest
	(*GetClaimStateResponse)(nil),  // 14: pb.v1.GetClaimStateResponse
	(*v1.Exception)(nil),           // 15: common.v1.Exception
}
var file_pb_v1_oracle_proto_depIdxs = []int32{
	15, // 0: pb.v1.UploadClaimWF1Response.exception:type_name -> common.v1.Exception
	15, // 1: pb.v1.UploadClaimWF2Response.exception:type_name -> common.v1.Exception
	15, // 2: pb.v1.UploadClaimWF3Response.exception:type_name -> common.v1.Exception
	6,  // 3: pb.v1.UploadClaimWF4Request.line_items:type_name -> pb.v1.LineItem
	15, // 4: pb.v1.UploadClaimWF4Response.exception:type_name -> common.v1.Exception
	15, // 5: pb.v1.UploadClaimWF5Response.exception:type_name -> common.v1.Exception
	15, // 6: pb.v1.InvokeProcessResponse.exception:type_name -> common.v1.Exception
	15, // 7: pb.v1.GetClaimStateResponse.exception:type_name -> common.v1.Exception
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pb_v1_oracle_proto_init() }
func file_pb_v1_oracle_proto_init() {
	if File_pb_v1_oracle_proto != nil {
		return
	}
	file_pb_v1_oracle_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadClaimWF1Response_Exception)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[3].OneofWrappers = []any{
		(*UploadClaimWF2Response_Exception)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[5].OneofWrappers = []any{
		(*UploadClaimWF3Response_Exception)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[8].OneofWrappers = []any{
		(*UploadClaimWF4Response_Exception)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[10].OneofWrappers = []any{
		(*UploadClaimWF5Response_Exception)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[12].OneofWrappers = []any{
		(*InvokeProcessResponse_Exception)(nil),
	}
	file_pb_v1_oracle_proto_msgTypes[14].OneofWrappers = []any{
		(*GetClaimStateResponse_Exception)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_v1_oracle_proto_rawDesc), len(file_pb_v1_oracle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_v1_oracle_proto_goTypes,
		DependencyIndexes: file_pb_v1_oracle_proto_depIdxs,
		MessageInfos:      file_pb_v1_oracle_proto_msgTypes,
	}.Build()
	File_pb_v1_oracle_proto = out.File
	file_pb_v1_oracle_proto_goTypes = nil
	file_pb_v1_oracle_proto_depIdxs = nil
}
