// Copyright © 2024 Luther Systems, Ltd. All right reserved.

// API Specification and Documentation.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: srvpb/v1/oracle.proto

package srv

import (
	context "context"
	v1 "github.com/luthersystems/cdcs/api/pb/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CdcsService_UploadClaimWF1_FullMethodName = "/srvpb.v1.CdcsService/UploadClaimWF1"
	CdcsService_UploadClaimWF2_FullMethodName = "/srvpb.v1.CdcsService/UploadClaimWF2"
	CdcsService_UploadClaimWF3_FullMethodName = "/srvpb.v1.CdcsService/UploadClaimWF3"
	CdcsService_UploadClaimWF4_FullMethodName = "/srvpb.v1.CdcsService/UploadClaimWF4"
	CdcsService_UploadClaimWF5_FullMethodName = "/srvpb.v1.CdcsService/UploadClaimWF5"
	CdcsService_InvokeProcess_FullMethodName  = "/srvpb.v1.CdcsService/InvokeProcess"
	CdcsService_GetClaimState_FullMethodName  = "/srvpb.v1.CdcsService/GetClaimState"
)

// CdcsServiceClient is the client API for CdcsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CdcsServiceClient interface {
	UploadClaimWF1(ctx context.Context, in *v1.UploadClaimWF1Request, opts ...grpc.CallOption) (*v1.UploadClaimWF1Response, error)
	UploadClaimWF2(ctx context.Context, in *v1.UploadClaimWF2Request, opts ...grpc.CallOption) (*v1.UploadClaimWF2Response, error)
	UploadClaimWF3(ctx context.Context, in *v1.UploadClaimWF3Request, opts ...grpc.CallOption) (*v1.UploadClaimWF3Response, error)
	UploadClaimWF4(ctx context.Context, in *v1.UploadClaimWF4Request, opts ...grpc.CallOption) (*v1.UploadClaimWF4Response, error)
	UploadClaimWF5(ctx context.Context, in *v1.UploadClaimWF5Request, opts ...grpc.CallOption) (*v1.UploadClaimWF5Response, error)
	InvokeProcess(ctx context.Context, in *v1.InvokeProcessRequest, opts ...grpc.CallOption) (*v1.InvokeProcessResponse, error)
	GetClaimState(ctx context.Context, in *v1.GetClaimStateRequest, opts ...grpc.CallOption) (*v1.GetClaimStateResponse, error)
}

type cdcsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCdcsServiceClient(cc grpc.ClientConnInterface) CdcsServiceClient {
	return &cdcsServiceClient{cc}
}

func (c *cdcsServiceClient) UploadClaimWF1(ctx context.Context, in *v1.UploadClaimWF1Request, opts ...grpc.CallOption) (*v1.UploadClaimWF1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UploadClaimWF1Response)
	err := c.cc.Invoke(ctx, CdcsService_UploadClaimWF1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdcsServiceClient) UploadClaimWF2(ctx context.Context, in *v1.UploadClaimWF2Request, opts ...grpc.CallOption) (*v1.UploadClaimWF2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UploadClaimWF2Response)
	err := c.cc.Invoke(ctx, CdcsService_UploadClaimWF2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdcsServiceClient) UploadClaimWF3(ctx context.Context, in *v1.UploadClaimWF3Request, opts ...grpc.CallOption) (*v1.UploadClaimWF3Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UploadClaimWF3Response)
	err := c.cc.Invoke(ctx, CdcsService_UploadClaimWF3_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdcsServiceClient) UploadClaimWF4(ctx context.Context, in *v1.UploadClaimWF4Request, opts ...grpc.CallOption) (*v1.UploadClaimWF4Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UploadClaimWF4Response)
	err := c.cc.Invoke(ctx, CdcsService_UploadClaimWF4_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdcsServiceClient) UploadClaimWF5(ctx context.Context, in *v1.UploadClaimWF5Request, opts ...grpc.CallOption) (*v1.UploadClaimWF5Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UploadClaimWF5Response)
	err := c.cc.Invoke(ctx, CdcsService_UploadClaimWF5_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdcsServiceClient) InvokeProcess(ctx context.Context, in *v1.InvokeProcessRequest, opts ...grpc.CallOption) (*v1.InvokeProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.InvokeProcessResponse)
	err := c.cc.Invoke(ctx, CdcsService_InvokeProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cdcsServiceClient) GetClaimState(ctx context.Context, in *v1.GetClaimStateRequest, opts ...grpc.CallOption) (*v1.GetClaimStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetClaimStateResponse)
	err := c.cc.Invoke(ctx, CdcsService_GetClaimState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CdcsServiceServer is the server API for CdcsService service.
// All implementations must embed UnimplementedCdcsServiceServer
// for forward compatibility.
type CdcsServiceServer interface {
	UploadClaimWF1(context.Context, *v1.UploadClaimWF1Request) (*v1.UploadClaimWF1Response, error)
	UploadClaimWF2(context.Context, *v1.UploadClaimWF2Request) (*v1.UploadClaimWF2Response, error)
	UploadClaimWF3(context.Context, *v1.UploadClaimWF3Request) (*v1.UploadClaimWF3Response, error)
	UploadClaimWF4(context.Context, *v1.UploadClaimWF4Request) (*v1.UploadClaimWF4Response, error)
	UploadClaimWF5(context.Context, *v1.UploadClaimWF5Request) (*v1.UploadClaimWF5Response, error)
	InvokeProcess(context.Context, *v1.InvokeProcessRequest) (*v1.InvokeProcessResponse, error)
	GetClaimState(context.Context, *v1.GetClaimStateRequest) (*v1.GetClaimStateResponse, error)
	mustEmbedUnimplementedCdcsServiceServer()
}

// UnimplementedCdcsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCdcsServiceServer struct{}

func (UnimplementedCdcsServiceServer) UploadClaimWF1(context.Context, *v1.UploadClaimWF1Request) (*v1.UploadClaimWF1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadClaimWF1 not implemented")
}
func (UnimplementedCdcsServiceServer) UploadClaimWF2(context.Context, *v1.UploadClaimWF2Request) (*v1.UploadClaimWF2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadClaimWF2 not implemented")
}
func (UnimplementedCdcsServiceServer) UploadClaimWF3(context.Context, *v1.UploadClaimWF3Request) (*v1.UploadClaimWF3Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadClaimWF3 not implemented")
}
func (UnimplementedCdcsServiceServer) UploadClaimWF4(context.Context, *v1.UploadClaimWF4Request) (*v1.UploadClaimWF4Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadClaimWF4 not implemented")
}
func (UnimplementedCdcsServiceServer) UploadClaimWF5(context.Context, *v1.UploadClaimWF5Request) (*v1.UploadClaimWF5Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadClaimWF5 not implemented")
}
func (UnimplementedCdcsServiceServer) InvokeProcess(context.Context, *v1.InvokeProcessRequest) (*v1.InvokeProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeProcess not implemented")
}
func (UnimplementedCdcsServiceServer) GetClaimState(context.Context, *v1.GetClaimStateRequest) (*v1.GetClaimStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClaimState not implemented")
}
func (UnimplementedCdcsServiceServer) mustEmbedUnimplementedCdcsServiceServer() {}
func (UnimplementedCdcsServiceServer) testEmbeddedByValue()                     {}

// UnsafeCdcsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CdcsServiceServer will
// result in compilation errors.
type UnsafeCdcsServiceServer interface {
	mustEmbedUnimplementedCdcsServiceServer()
}

func RegisterCdcsServiceServer(s grpc.ServiceRegistrar, srv CdcsServiceServer) {
	// If the following call pancis, it indicates UnimplementedCdcsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CdcsService_ServiceDesc, srv)
}

func _CdcsService_UploadClaimWF1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UploadClaimWF1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdcsServiceServer).UploadClaimWF1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdcsService_UploadClaimWF1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdcsServiceServer).UploadClaimWF1(ctx, req.(*v1.UploadClaimWF1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdcsService_UploadClaimWF2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UploadClaimWF2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdcsServiceServer).UploadClaimWF2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdcsService_UploadClaimWF2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdcsServiceServer).UploadClaimWF2(ctx, req.(*v1.UploadClaimWF2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdcsService_UploadClaimWF3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UploadClaimWF3Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdcsServiceServer).UploadClaimWF3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdcsService_UploadClaimWF3_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdcsServiceServer).UploadClaimWF3(ctx, req.(*v1.UploadClaimWF3Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdcsService_UploadClaimWF4_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UploadClaimWF4Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdcsServiceServer).UploadClaimWF4(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdcsService_UploadClaimWF4_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdcsServiceServer).UploadClaimWF4(ctx, req.(*v1.UploadClaimWF4Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdcsService_UploadClaimWF5_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UploadClaimWF5Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdcsServiceServer).UploadClaimWF5(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdcsService_UploadClaimWF5_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdcsServiceServer).UploadClaimWF5(ctx, req.(*v1.UploadClaimWF5Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdcsService_InvokeProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.InvokeProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdcsServiceServer).InvokeProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdcsService_InvokeProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdcsServiceServer).InvokeProcess(ctx, req.(*v1.InvokeProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CdcsService_GetClaimState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetClaimStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CdcsServiceServer).GetClaimState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CdcsService_GetClaimState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CdcsServiceServer).GetClaimState(ctx, req.(*v1.GetClaimStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CdcsService_ServiceDesc is the grpc.ServiceDesc for CdcsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CdcsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "srvpb.v1.CdcsService",
	HandlerType: (*CdcsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadClaimWF1",
			Handler:    _CdcsService_UploadClaimWF1_Handler,
		},
		{
			MethodName: "UploadClaimWF2",
			Handler:    _CdcsService_UploadClaimWF2_Handler,
		},
		{
			MethodName: "UploadClaimWF3",
			Handler:    _CdcsService_UploadClaimWF3_Handler,
		},
		{
			MethodName: "UploadClaimWF4",
			Handler:    _CdcsService_UploadClaimWF4_Handler,
		},
		{
			MethodName: "UploadClaimWF5",
			Handler:    _CdcsService_UploadClaimWF5_Handler,
		},
		{
			MethodName: "InvokeProcess",
			Handler:    _CdcsService_InvokeProcess_Handler,
		},
		{
			MethodName: "GetClaimState",
			Handler:    _CdcsService_GetClaimState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "srvpb/v1/oracle.proto",
}
